import { v4 } from "uuid";

export const projectList = [
  {
    id: v4(),
    title: "Up-ToDo",
    desc: "Effortlessly manage tasks across devices with our platform. Join now for seamless task organization and synchronization!",
    languages: [
      "ReactJS",
      "Typescript",
      "Redux toolkit",
      "Rtk Query",
      "Vite",
      "Jest",
      "CI/CD",
      "NestJs",
      "MongoDB",
      "Mongoose",
    ],
    poster: "https://i.ibb.co/Xp8HWXn/todo.png",
    liveUrl: "https://up-todo.vercel.app",
    githubUrl: "https://github.com/BielowAlex/up-todo",
  },
  {
    id: v4(),
    title: "AlexFilms",
    desc: 'A website for trailers of the latest movies, utilizing the "TMDB API" with search functionality and various filters. The design is a Netflix clone.',
    languages: ["ReactJS", "Typescript", "Redux toolkit", "RestAPI"],
    poster: "https://i.ibb.co/926hJZQ/alexfilms.webp",
    liveUrl: "https://alex-films.vercel.app/",
    githubUrl: "https://github.com/BielowAlex/alex_films_react",
  },
  {
    id: v4(),
    title: "Movieland",
    desc: "Commercial project in team Expletech. Landing page for the Cinema with admin dashboard. ",
    languages: [
      "NextJs",
      "Typescript",
      "Redux toolkit",
      "NestJS",
      "Typeorm",
      "Aws S3",
      "Jest",
    ],
    poster: "https://i.ibb.co/rvCW9KL/movieland.webp",
    liveUrl: "https://www.movieland.com.ua/",
    githubUrl: null,
  },
  {
    id: v4(),
    title: "My Portfolio",
    desc: "My portfolio, a simple landing page with an admin dashboard, a bit of animation, and a bit of love",
    languages: [
      "ReactJS",
      "Typescript",
      "Redux toolkit",
      "Axios",
      "RestAPI",
      "Jest",
      "CI/CD",
    ],
    poster: "https://i.ibb.co/qjxxGjc/portfolio.webp",
    liveUrl: null,
    githubUrl: "https://github.com/BielowAlex/portfolio-frontend",
  },
];
